"""Workbook vocabulary loaded from data, never used as catalog classification rules."""

from core.resource_config import load_resource

_LABELS = load_resource("workbook_labels.json")

ARTICLE_COLUMN = _LABELS["ARTICLE_COLUMN"]
FAMILY_COLUMN = _LABELS["FAMILY_COLUMN"]
QUANTITY_COLUMN = _LABELS["QUANTITY_COLUMN"]
SIZE_COLUMN = _LABELS["SIZE_COLUMN"]
PRICE_COLUMN = _LABELS["PRICE_COLUMN"]
COST_COLUMN = _LABELS["COST_COLUMN"]
SALES_VALUE_LABEL = _LABELS["SALES_VALUE_LABEL"]
DATABASE_ORIGIN_COLUMN = _LABELS["DATABASE_ORIGIN_COLUMN"]
RAW_DATA_SHEET = _LABELS["RAW_DATA_SHEET"]
DEFAULT_FAMILY = _LABELS["DEFAULT_FAMILY"]
SYSTEM_STOCK_COLUMN = _LABELS["SYSTEM_STOCK_COLUMN"]
PHYSICAL_COUNT_COLUMN = _LABELS["PHYSICAL_COUNT_COLUMN"]
DIFFERENCE_COLUMN = _LABELS["DIFFERENCE_COLUMN"]
COST_TOTAL_COLUMN = _LABELS["COST_TOTAL_COLUMN"]
SALES_TOTAL_COLUMN = _LABELS["SALES_TOTAL_COLUMN"]
REVIEW_FAMILY = _LABELS["REVIEW_FAMILY"]
REVIEW_PREFIX = _LABELS["REVIEW_PREFIX"]
UNIT_COST_PREFIX = _LABELS["UNIT_COST_PREFIX"]
UNIT_SALES_PREFIX = _LABELS["UNIT_SALES_PREFIX"]
MARGIN_PREFIX = _LABELS["MARGIN_PREFIX"]
UNMATCHED_FAMILY = _LABELS["UNMATCHED_FAMILY"]
